---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/hjnblcom/public_html/myapp
    - source /home2/hjnblcom/nodevenv/public_html/myapp/22/bin/activate && cd /home2/hjnblcom/public_html/myapp && npm install